-- ═══════════════════════════════════════════════════════════════════════════
-- PO Modernization Demo Seed Data
-- This file is auto-loaded by Spring Boot for H2 database
-- ═══════════════════════════════════════════════════════════════════════════

-- Part 2: Live Workflow Demo - Nike Korea PO
INSERT INTO PO (POKEY, STORERKEY, EXTERNPOKEY, FACILITY, SUPPLIERKEY, STATUS, POTYPE, ORDERDATE, EXPECTEDDATE, ADDWHO, ADDDATE, VERSION) VALUES
('PO-DEMO-001', 'NIKE', 'NIKE-EXT-001', 'KR01', 'NIKE-SUPPLIER-001', '0', 'STANDARD', CURRENT_TIMESTAMP, DATEADD('DAY', 7, CURRENT_DATE), 'SYSTEM', CURRENT_TIMESTAMP, 0);

-- Part 3: Saga Compensation Demo - Failure Simulation PO
INSERT INTO PO (POKEY, STORERKEY, EXTERNPOKEY, FACILITY, SUPPLIERKEY, STATUS, POTYPE, ORDERDATE, EXPECTEDDATE, ADDWHO, ADDDATE, VERSION) VALUES
('PO-FAIL-DEMO', 'NIKE', 'NIKE-FAIL-001', 'KR01', 'NIKE-SUPPLIER-002', '0', 'STANDARD', CURRENT_TIMESTAMP, DATEADD('DAY', 7, CURRENT_DATE), 'SYSTEM', CURRENT_TIMESTAMP, 0);

-- Part 4: Client Plugin Demo - H&M Singapore PO
INSERT INTO PO (POKEY, STORERKEY, EXTERNPOKEY, FACILITY, SUPPLIERKEY, STATUS, POTYPE, ORDERDATE, EXPECTEDDATE, ADDWHO, ADDDATE, VERSION) VALUES
('PO-HM-SG-001', 'HM', 'HM-SG-EXT-001', 'SG01', 'HM-SUPPLIER-ASIA', '0', 'FAST', CURRENT_TIMESTAMP, DATEADD('DAY', 5, CURRENT_DATE), 'SYSTEM', CURRENT_TIMESTAMP, 0);

-- Nike India PO
INSERT INTO PO (POKEY, STORERKEY, EXTERNPOKEY, FACILITY, SUPPLIERKEY, STATUS, POTYPE, ORDERDATE, EXPECTEDDATE, ADDWHO, ADDDATE, VERSION) VALUES
('PO-NIKE-IN-001', 'NIKE', 'NIKE-IN-EXT-001', 'IN01', 'NIKE-SUPPLIER-INDIA', '0', 'STANDARD', CURRENT_TIMESTAMP, DATEADD('DAY', 14, CURRENT_DATE), 'SYSTEM', CURRENT_TIMESTAMP, 0);

-- Cross-Dock Demo PO
INSERT INTO PO (POKEY, STORERKEY, EXTERNPOKEY, FACILITY, SUPPLIERKEY, STATUS, POTYPE, ORDERDATE, EXPECTEDDATE, ADDWHO, ADDDATE, VERSION) VALUES
('PO-XDOCK-001', 'NIKE', 'NIKE-XDOCK-EXT', 'KR01', 'NIKE-SUPPLIER-XDOCK', '0', 'XDOCK', CURRENT_TIMESTAMP, DATEADD('DAY', 3, CURRENT_DATE), 'SYSTEM', CURRENT_TIMESTAMP, 0);

-- Batch Processing Demo POs
INSERT INTO PO (POKEY, STORERKEY, EXTERNPOKEY, FACILITY, SUPPLIERKEY, STATUS, POTYPE, ORDERDATE, EXPECTEDDATE, ADDWHO, ADDDATE, VERSION) VALUES
('PO-BATCH-001', 'NIKE', 'NIKE-BATCH-001', 'KR01', 'NIKE-SUPPLIER-BATCH', '0', 'STANDARD', CURRENT_TIMESTAMP, DATEADD('DAY', 7, CURRENT_DATE), 'SYSTEM', CURRENT_TIMESTAMP, 0),
('PO-BATCH-002', 'NIKE', 'NIKE-BATCH-002', 'KR01', 'NIKE-SUPPLIER-BATCH', '0', 'STANDARD', CURRENT_TIMESTAMP, DATEADD('DAY', 7, CURRENT_DATE), 'SYSTEM', CURRENT_TIMESTAMP, 0),
('PO-BATCH-003', 'NIKE', 'NIKE-BATCH-003', 'KR01', 'NIKE-SUPPLIER-BATCH', '0', 'STANDARD', CURRENT_TIMESTAMP, DATEADD('DAY', 7, CURRENT_DATE), 'SYSTEM', CURRENT_TIMESTAMP, 0);

-- Receipt for PO-DEMO-001 (ready for finalization)
INSERT INTO RECEIPT (RECEIPTKEY, STORERKEY, EXTERNRECEIPTKEY, FACILITY, STATUS, RECEIPTTYPE, RECEIPTDATE, ADDWHO, ADDDATE, VERSION) VALUES
('RCV-DEMO-001', 'NIKE', 'RCV-EXT-DEMO-001', 'KR01', '0', 'NORMAL', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 0);

-- Receipt Details with Lottables
INSERT INTO RECEIPTDETAIL (RECEIPTDETAILKEY, RECEIPTKEY, RECEIPTLINENUMBER, SKU, QTYEXPECTED, QTYRECEIVED, UOM, PACKKEY, STATUS, POKEY, POLINENUMBER, LOTTABLE01, LOTTABLE02, LOTTABLE03, ADDWHO, ADDDATE) VALUES
('RCV-DEMO-001-001', 'RCV-DEMO-001', 1, 'NK-AIRMAX90-BLK-10', 100, 100, 'EA', 'STD', '0', 'PO-DEMO-001', 1, 'STYLE-AM90', 'COLOR-BLK', 'SIZE-10', 'SYSTEM', CURRENT_TIMESTAMP),
('RCV-DEMO-001-002', 'RCV-DEMO-001', 2, 'NK-AIRMAX90-WHT-10', 150, 150, 'EA', 'STD', '0', 'PO-DEMO-001', 2, 'STYLE-AM90', 'COLOR-WHT', 'SIZE-10', 'SYSTEM', CURRENT_TIMESTAMP),
('RCV-DEMO-001-003', 'RCV-DEMO-001', 3, 'NK-AF1-BLK-9', 200, 200, 'EA', 'STD', '0', 'PO-DEMO-001', 3, 'STYLE-AF1', 'COLOR-BLK', 'SIZE-9', 'SYSTEM', CURRENT_TIMESTAMP);
