-- PO Modernization Database Schema

-- Orders (PO Header)
CREATE TABLE IF NOT EXISTS ORDERS (
    POKEY VARCHAR(20) PRIMARY KEY,
    STORERKEY VARCHAR(20) NOT NULL,
    EXTERNPOKEY VARCHAR(50),
    FACILITY VARCHAR(20) NOT NULL,
    SUPPLIERKEY VARCHAR(50),
    STATUS VARCHAR(5) DEFAULT '0',
    TYPE VARCHAR(10),
    PODATE TIMESTAMP,
    EXPECTEDRECEIPTDATE TIMESTAMP,
    ADDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADDWHO VARCHAR(50),
    EDITDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EDITWHO VARCHAR(50)
);

-- Order Details (PO Lines)
CREATE TABLE IF NOT EXISTS ORDERDETAIL (
    ORDERDETAILKEY VARCHAR(30) PRIMARY KEY,
    POKEY VARCHAR(20) NOT NULL,
    ORDERLINENUMBER INT NOT NULL,
    SKU VARCHAR(50) NOT NULL,
    QTYORDERED DECIMAL(18,4),
    QTYRECEIVED DECIMAL(18,4) DEFAULT 0,
    UNITPRICE DECIMAL(18,4),
    STATUS VARCHAR(5) DEFAULT '0',
    PACKKEY VARCHAR(20),
    UOM VARCHAR(10),
    LOTTABLE01 VARCHAR(50),
    LOTTABLE02 VARCHAR(50),
    LOTTABLE03 VARCHAR(50),
    LOTTABLE04 VARCHAR(50),
    LOTTABLE05 VARCHAR(50),
    ADDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADDWHO VARCHAR(50),
    EDITDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EDITWHO VARCHAR(50),
    FOREIGN KEY (POKEY) REFERENCES ORDERS(POKEY)
);

-- Receipt Header
CREATE TABLE IF NOT EXISTS RECEIPT (
    RECEIPTKEY VARCHAR(20) PRIMARY KEY,
    STORERKEY VARCHAR(20) NOT NULL,
    EXTERNRECEIPTKEY VARCHAR(50),
    FACILITY VARCHAR(20) NOT NULL,
    STATUS VARCHAR(5) DEFAULT '0',
    TYPE VARCHAR(10),
    RECEIPTDATE TIMESTAMP,
    ADDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADDWHO VARCHAR(50),
    EDITDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EDITWHO VARCHAR(50)
);

-- Receipt Details
CREATE TABLE IF NOT EXISTS RECEIPTDETAIL (
    RECEIPTDETAILKEY VARCHAR(30) PRIMARY KEY,
    RECEIPTKEY VARCHAR(20) NOT NULL,
    RECEIPTLINENUMBER INT NOT NULL,
    POKEY VARCHAR(20),
    POLINENUMBER INT,
    SKU VARCHAR(50) NOT NULL,
    LOT VARCHAR(50),
    LOC VARCHAR(20),
    ID VARCHAR(50),
    QTYEXPECTED DECIMAL(18,4),
    QTYRECEIVED DECIMAL(18,4) DEFAULT 0,
    PACKKEY VARCHAR(20),
    LOTTABLE01 VARCHAR(50),
    LOTTABLE02 VARCHAR(50),
    LOTTABLE03 VARCHAR(50),
    LOTTABLE04 VARCHAR(50),
    LOTTABLE05 VARCHAR(50),
    ADDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADDWHO VARCHAR(50),
    EDITDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EDITWHO VARCHAR(50),
    FOREIGN KEY (RECEIPTKEY) REFERENCES RECEIPT(RECEIPTKEY)
);

-- Receipt to PO Link
CREATE TABLE IF NOT EXISTS RECEIPTPO (
    RECEIPTKEY VARCHAR(20) NOT NULL,
    POKEY VARCHAR(20) NOT NULL,
    ADDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADDWHO VARCHAR(50),
    PRIMARY KEY (RECEIPTKEY, POKEY),
    FOREIGN KEY (RECEIPTKEY) REFERENCES RECEIPT(RECEIPTKEY),
    FOREIGN KEY (POKEY) REFERENCES ORDERS(POKEY)
);

-- Inventory (LOT x Location x ID)
CREATE TABLE IF NOT EXISTS LOTxLOCxID (
    LOTXLOCXIDKEY VARCHAR(50) PRIMARY KEY,
    STORERKEY VARCHAR(20) NOT NULL,
    SKU VARCHAR(50) NOT NULL,
    LOT VARCHAR(50),
    LOC VARCHAR(20) NOT NULL,
    ID VARCHAR(50),
    QTY DECIMAL(18,4) DEFAULT 0,
    QTYALLOCATED DECIMAL(18,4) DEFAULT 0,
    QTYPICKED DECIMAL(18,4) DEFAULT 0,
    STATUS VARCHAR(10),
    RECEIPTKEY VARCHAR(20),
    ADDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADDWHO VARCHAR(50),
    EDITDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EDITWHO VARCHAR(50)
);

-- Key Generator Counter
CREATE TABLE IF NOT EXISTS NCOUNTER (
    TABLENAME VARCHAR(50) PRIMARY KEY,
    COUNTER BIGINT DEFAULT 0
);

-- Initialize counters
INSERT INTO NCOUNTER (TABLENAME, COUNTER) VALUES ('ORDERS', 0);
INSERT INTO NCOUNTER (TABLENAME, COUNTER) VALUES ('ORDERDETAIL', 0);
INSERT INTO NCOUNTER (TABLENAME, COUNTER) VALUES ('RECEIPT', 0);
INSERT INTO NCOUNTER (TABLENAME, COUNTER) VALUES ('RECEIPTDETAIL', 0);
